# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestregistrationautomation():
  def setup_method(self, method):
    chrome_driver_binary = "./chromedriver 2"
    ser_chrome = Service(chrome_driver_binary)
    self.driver = webdriver.Chrome(service=ser_chrome)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testregistrationautomation(self):
    self.driver.get("https://www.calvinklein.us/en")
    self.driver.set_window_size(1440, 812)
    self.driver.find_element(By.CSS_SELECTOR, "#headerLogin > .black-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-sign-up").click()


  
